- hosts: jenkins
  become: yes
  gather_facts: true

  # Tell every yum module in this play to use classic Yum‑3
  vars:
    ansible_yum_use_backend: yum        # <- one line, play‑wide

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto     # switch to java‑11 if you want
          - git
        state: present

    - name: Add Jenkins repo GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
- hosts: jenkins
  become: yes
  gather_facts: true

  # Tell every yum module in this play to use classic Yum‑3
  vars:
    ansible_yum_use_backend: yum        # <- one line, play‑wide

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto     # switch to java‑11 if you want
          - git
        state: present

    - name: Add Jenkins repo GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
- hosts: jenkins
  become: yes
  gather_facts: true

  # Tell every yum module in this play to use classic Yum‑3
  vars:
    ansible_yum_use_backend: yum        # <- one line, play‑wide

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto     # switch to java‑11 if you want
          - git
        state: present

    - name: Add Jenkins repo GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
