---
# Playbook to install Apache Maven on the same EC2 host via shell for pkg_mgr shims
- hosts: jenkins
  become: yes
  gather_facts: true

  tasks:
    - name: Enable EPEL repository
      shell: |
        yum install -y epel-release
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Install Apache Maven
      shell: |
        yum install -y maven
      args:
        creates: /usr/bin/mvn

    - name: Verify Maven installation
      shell: mvn --version
      register: maven_output
      changed_when: false

    - name: Display Maven version
      debug:
        var: maven_output.stdout_lines
