# playbooks/install-jenkins.yml  — works on AL2 + ansible‑core 2.18+

- hosts: jenkins
  become: yes
  gather_facts: true

  tasks:
    #######################################################################
    # 1. Install Java 17 and Git (only if not yet present)
    #######################################################################
    - name: Install Java 17 and Git
      shell: yum install -y java-17-amazon-corretto git
      args:
        creates: /usr/lib/jvm/java-17-amazon-corretto    # if this path exists, yum isn't called

    #######################################################################
    # 2. Import Jenkins GPG key (skipped if already in the RPM DB)
    #######################################################################
    - name: Import Jenkins GPG key
      shell: rpm --import https://pkg.jenkins.io/redhat/jenkins.io-2023.key
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins

    #######################################################################
    # 3. Add Jenkins repo file (overwrites only when content changes)
    #######################################################################
    - name: Add Jenkins yum repo
      copy:
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'
        content: |
          [jenkins]
          name=Jenkins
          baseurl=https://pkg.jenkins.io/redhat-stable
          gpgcheck=1
          gpgkey=https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    #######################################################################
    # 4. Install the Jenkins package (skips if already installed)
    #######################################################################
    - name: Install Jenkins
      shell: yum install -y jenkins
      args:
        creates: /usr/lib/jenkins/jenkins.war

    #######################################################################
    # 5. Enable and start the Jenkins service
    #######################################################################
    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
