###############################################################################
# playbooks/install-jenkins.yml
###############################################################################
- hosts: jenkins
  gather_facts: false       # can't gather until Python ≥3.8 exists
  become: yes
  tasks:

    - name: Install Python 3.11 if not already present
    raw: |
      if [ ! -x /usr/bin/python3.11 ]; then
        amazon-linux-extras enable python3.11 &&
        yum clean metadata &&
        yum -y install python3.11 &&
        alternatives --set python3 /usr/bin/python3.11
      fi
    changed_when: false
    check_mode: no          # ← ensures task runs even when Semaphore uses --check



    - name: Tell Ansible to use the new interpreter from now on
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.11

# --------------------------------------------------------------------------- #
# Everything below here stays exactly as you have it
# --------------------------------------------------------------------------- #
- hosts: jenkins
  become: yes
  gather_facts: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto
          - git
        state: present

    - name: Add Jenkins repo key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started

