# playbooks/install-jenkins.yml  (shortened)

- hosts: jenkins
  gather_facts: false
  become: yes
  tasks:
    - name: Ensure Python ≥ 3.8 is present
      raw: |
        if python3 - <<'PY'
        import sys
        sys.exit(0) if sys.version_info >= (3, 8) else sys.exit(1)
        PY
        then
          echo "python OK"
        else
          amazon-linux-extras enable python3.11
          yum clean metadata
          yum -y install python3.11
        fi
    - set_fact:
        ansible_python_interpreter: /usr/bin/python3.11

- hosts: jenkins
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto   # or java‑11
          - git
        state: present

    - name: Add Jenkins repo key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
