- hosts: jenkins
  gather_facts: true
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto   # use java‑11 if you prefer
          - git
        state: present

    - name: Add Jenkins repo GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
