- hosts: jenkins
  become: yes
  gather_facts: true

  tasks:
    #####################################################################
    # 1. Install Java 17 + Git (runs once)
    #####################################################################
    - name: Install Java 17 and Git
      shell: yum install -y java-17-amazon-corretto git
      args:
        creates: /usr/lib/jvm/java-17-amazon-corretto   # idempotent

    #####################################################################
    # 2. Import Jenkins GPG key (skips if already imported)
    #####################################################################
    - name: Import Jenkins GPG key
      shell: rpm --import https://pkg.jenkins.io/redhat/jenkins.io-2023.key
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins

    #####################################################################
    # 3. Add Jenkins repository
    #####################################################################
    - name: Add Jenkins yum repo
      copy:
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'
        content: |
          [jenkins]
          name=Jenkins
          baseurl=https://pkg.jenkins.io/redhat-stable
          gpgcheck=1
          gpgkey=https://pkg.jenkins.io/redhat/jenkins.io-2023.key
      notify: restart jenkins     # repo change → restart later

    #####################################################################
    # 4. Install Jenkins package (once)
    #####################################################################
    - name: Install Jenkins
      shell: yum install -y jenkins
      args:
        creates: /usr/lib/jenkins/jenkins.war
      notify: restart jenkins

    #####################################################################
    # 5. Disable setup‑wizard & create admin user (Groovy)
    #####################################################################
    - name: Disable setup wizard
      lineinfile:
        path: /etc/sysconfig/jenkins
        regexp: '^JENKINS_JAVA_OPTIONS='
        line: 'JENKINS_JAVA_OPTIONS="-Djenkins.install.runSetupWizard=false"'
      notify: restart jenkins

    - name: Drop Groovy init script to create admin user
      copy:
        dest: /var/lib/jenkins/init.groovy.d/01_create_admin.groovy
        owner: jenkins
        group: jenkins
        mode: '0644'
        content: |
          import jenkins.model.*
          import hudson.security.*
          def instance = Jenkins.getInstance()
          def hudsonRealm = new HudsonPrivateSecurityRealm(false)
          hudsonRealm.createAccount("ciadmin", "S3cret!")
          instance.setSecurityRealm(hudsonRealm)
          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          strategy.setAllowAnonymousRead(false)
          instance.setAuthorizationStrategy(strategy)
          instance.save()
      notify: restart jenkins

    #####################################################################
    # 6. Ensure service is enabled & running (will restart if notified)
    #####################################################################
    - name: Enable Jenkins service
      service:
        name: jenkins
        enabled: yes
        state: started

###########################################################################
# Handlers – **flush‑left**, sibling of tasks/vars/hosts
###########################################################################
handlers:
  - name: restart jenkins
    service:
      name: jenkins
      state: restarted
