###############################################################################
# 1. Bootstrap – make sure the host has Python ≥ 3.8
###############################################################################
- hosts: jenkins
  gather_facts: false
  become: yes

  tasks:
    - name: Ensure python38 is available and set as python3
      raw: |
        # If python3 is already ≥3.8 we're done
        python3 - <<'PY'
import sys
sys.exit(0) if sys.version_info >= (3,8) else sys.exit(1)
PY
        if [ $? -eq 0 ]; then exit 0; fi

        # Enable EPEL repo if python38 isn't found
        yum -q list python38 >/dev/null 2>&1 || (
          amazon-linux-extras enable epel &&
          yum clean metadata
        )

        # Install python38 and set the alternatives link
        yum -y install python38 &&
        alternatives --set python3 /usr/bin/python3.8
      changed_when: false
      check_mode: no

    - name: Tell Ansible to use the new interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
