###############################################################################
# 1. Bootstrap – be sure Python ≥ 3.8 exists
###############################################################################
- hosts: jenkins
  gather_facts: false
  become: yes

  tasks:
    - name: Ensure python38 is available and set as python3
      raw: |
        # Exit early if python3 is already ≥ 3.8
        python3 - <<'PY'
        import sys
        sys.exit(0) if sys.version_info >= (3, 8) else sys.exit(1)
        PY
        [ $? -eq 0 ] && exit 0

        # If python38 isn't found, bring in EPEL first
        if ! yum -q list python38 >/dev/null 2>&1; then
          # Install the release RPM (adds the repo file under /etc/yum.repos.d)
          yum -y install epel-release
          yum clean metadata
        fi

        # Now install python38 and flip the alternatives link
        yum -y install python38
        alternatives --set python3 /usr/bin/python3.8
      changed_when: false
      check_mode: no
