---
- name: Install and configure kubectl on eks-bootstrap server
  hosts: eks-bootstrap
  become: yes

  vars:
    eks_cluster_name: webapp-cluster
    eks_region: us-east-1
    kubectl_version: "1.30.0"

  tasks:
    - name: Install curl 
      become: yes
      command: yum install -y curl

    - name: Install unzip
      become: yes
      command: yum install -y unzip

    - name: Download kubectl binary
      become: yes
      shell: curl -Lo /usr/local/bin/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl

    - name: Verify kubectl installation
      command: kubectl version --client --short
      register: kubectl_version_check

    - name: Show kubectl version
      debug:
        msg: "{{ kubectl_version_check.stdout }}"

    - name: Ensure awscli is installed
      package:
        name: awscli
        state: present

    - name: Update kubeconfig for EKS cluster
      command: >
        aws eks update-kubeconfig
        --region {{ eks_region }}
        --name {{ eks_cluster_name }}
      environment:
        AWS_PROFILE: default
