---
- name: Install and configure kubectl on eks-bootstrap server
  hosts: eks-bootstrap
  become: yes

  vars:
    eks_cluster_name: webapp-cluster
    eks_region: us-east-1
    kubectl_version: "1.30.0"

  tasks:
    - name: Install curl 
      become: yes
      command: yum install -y curl

    - name: Install unzip
      become: yes
      command: yum install -y unzip

    - name: Download kubectl binary
      become: yes
      shell: curl -Lo /usr/local/bin/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl

    - name: Verify kubectl installation
      command: /usr/local/bin/kubectl version --client
      register: kubectl_version_check

    - name: Show kubectl version
      debug:
        msg: "{{ kubectl_version_check.stdout }}"

    - name: Download AWS CLI v2 installer
      become: yes
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    
    - name: Unzip AWS CLI v2 installer
      become: yes
      shell: unzip -o awscliv2.zip
    
    - name: Install AWS CLI v2
      become: yes
      shell: ./aws/install --update
    
    - name: Verify AWS CLI v2
      become: yes
      shell: /usr/local/bin/aws --version
      register: awscli_check
    
    - name: Show AWS CLI version
      debug:
        var: awscli_check.stdout
    
    - name: Configure kubeconfig for EKS cluster
      command: aws eks update-kubeconfig --name {{ eks_cluster_name }} --region {{ eks_region }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ eks_region }}"
