###############################################################################
# playbooks/install-jenkins.yml
###############################################################################
- hosts: jenkins
  gather_facts: false
  become: yes
  tasks:

    - name: Ensure Python ≥ 3.8 is present
      raw: |
        if python3 - <<'PY'
import sys, os
sys.exit(0) if sys.version_info >= (3,8) else sys.exit(1)
PY
        then exit 0; fi
        yum -y install python38
        alternatives --set python3 /usr/bin/python3.8
      changed_when: false
      check_mode: no

    - set_fact:
        ansible_python_interpreter: /usr/bin/python3


# --------------------------------------------------------------------------- #
# Everything below here stays exactly as you have it
# --------------------------------------------------------------------------- #
- hosts: jenkins
  become: yes
  gather_facts: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto
          - git
        state: present

    - name: Add Jenkins repo key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started

