# playbooks/test-connectivity.yml
- hosts: jenkins          # or whatever group/host you’ve defined
  gather_facts: false     # keeps it ultra‑fast
  tasks:
    - name: Ping the host
      ansible.builtin.ping:

