###############################################################################
# playbooks/install-jenkins.yml
###############################################################################

###############################################################################
# 1. Bootstrap – make sure Python ≥ 3.8 is available
###############################################################################
- hosts: jenkins
  gather_facts: false
  become: yes

  tasks:
    - name: Ensure python38 exists and /usr/bin/python3 points to it
      raw: |
        bash -c '
          # stop immediately if python3 already satisfies ≥3.8
          python3 - <<EOF
import sys, sysconfig
sys.exit(0) if sys.version_info >= (3, 8) else sys.exit(1)
EOF
          [ $? -eq 0 ] && exit 0

          # add EPEL repo if python38 not yet visible
          yum -q list python38 >/dev/null 2>&1 \
            || { yum -y install epel-release && yum clean metadata; }

          # install python38 and switch the alternatives link
          yum -y install python38 &&
          alternatives --set python3 /usr/bin/python3.8
        '
      changed_when: false        # keeps Ansible output tidy
      check_mode: no             # forces execution even in --check runs

    - name: Tell Ansible to use the upgraded interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

###############################################################################
# 2. Main play – install Java, add Jenkins repo, install & start Jenkins
###############################################################################
- hosts: jenkins
  gather_facts: true
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto   # use java‑11 if you prefer
          - git
        state: present

    - name: Add Jenkins repo GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
