###############################################################################
# playbooks/install-jenkins.yml
###############################################################################

###############################################################################
# 1. Bootstrap – make sure the host has Python ≥ 3.8
###############################################################################
- hosts: jenkins
  gather_facts: false          # can’t gather until Python is upgraded
  become: yes

  tasks:
    - name: Ensure python38 is installed and set as python3
      raw: |
        # Install python38 only if it’s missing
        rpm -q python38 >/dev/null 2>&1 || yum -y install python38
        # Point /usr/bin/python3 at the new binary
        alternatives --set python3 /usr/bin/python3.8
      changed_when: false      # keep Ansible output tidy
      check_mode: no           # force execution even if template runs with --check

    - name: Tell Ansible to use the upgraded interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

###############################################################################
# 2. Main play – install Java, add Jenkins repo, install & start Jenkins
###############################################################################
- hosts: jenkins
  gather_facts: true
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto   # switch to java‑11 if you prefer
          - git
        state: present

    - name: Add Jenkins repo GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable & start Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
