---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: no

  collections:
    - kubernetes.core

  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Apply Webapp Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"

    - name: Apply Webapp Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
