---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: no
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Ensure python3 & pip3 are installed
      become: yes
      yum:
        name:
          - python3   # on AL2 this will pull in the default python3 package (which includes pip3)
          - python3-pip
        state: present

    - name: Install Kubernetes Python client
      become: yes
      pip:
        name: kubernetes
        executable: pip3

    - name: Apply Webapp Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"

    - name: Apply Webapp Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
