---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: yes                      # <–– we need facts to detect pkg_mgr
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:

    # on AL2 (yum)
    - name: Install python3 & pip3 via yum
      when: ansible_facts.pkg_mgr == 'yum'
      become: yes
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install python3 & pip3 via dnf
      when: ansible_facts.pkg_mgr == 'dnf'
      become: yes
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
        state: present
        use_backend: dnf5

    - name: Install Kubernetes Python client
      become: yes
      ansible.builtin.pip:
        name: kubernetes
        executable: pip3

    - name: Apply Webapp Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"

    - name: Apply Webapp Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
