---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: no
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Ensure python3 & pip3 are installed
      become: yes
      ansible.builtin.yum:
        name:
          - python3          # amazon‑linux‑extras maps this to python3.x
          - python3-pip
        state: present
        use_backend: auto    # default; dnf5 on AL2023, yum/dnf4 on AL2

    - name: Install Kubernetes Python client
      become: yes
      pip:
        name: kubernetes
        executable: pip3

    - name: Apply Webapp Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"

    - name: Apply Webapp Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
