- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: yes
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    - name: Enable Python 3.8 and install pip
      become: yes
      ansible.builtin.shell: |
        amazon-linux-extras enable python3.8
        yum clean metadata
        yum install -y python3.8 python3.8-pip
      args:
        warn: false

    - name: Install the Kubernetes Python client into Python 3.8
      become: yes
      ansible.builtin.pip:
        executable: /usr/bin/python3.8 -m pip
        name:
          - kubernetes
          - kubernetes-asyncio

    - name: Apply Webapp Deployment
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"

    - name: Apply Webapp Service
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
