---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: yes                   # <–– enable fact-gathering so ansible_pkg_mgr is set
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config
    ansible_python_interpreter: /usr/bin/python3   # <–– point Ansible at the system Python

  tasks:
    - name: Install python3 & pip3
      become: yes
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Kubernetes Python client
      become: yes
      pip:
        name: kubernetes
        executable: /usr/bin/pip3          # <–– install into the same interpreter

    - name: Apply Webapp Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"

    - name: Apply Webapp Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
