---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: no

  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Apply Webapp Deployment manifest
      command: >
        kubectl apply
          --kubeconfig {{ kubeconfig_path }}
          -f {{ playbook_dir }}/webapp-deployment.yaml

    - name: Apply Webapp Service manifest
      command: >
        kubectl apply
          --kubeconfig {{ kubeconfig_path }}
          -f {{ playbook_dir }}/webapp-service.yaml
