---
- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: no

  collections:
    - community.kubernetes

  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Apply Webapp Deployment manifest
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: k8s/webapp-deployment.yaml

    - name: Apply Webapp Service manifest
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: k8s/webapp-service.yaml
