---
- name: Deploy regapp application to Kubernetes (EKS)
  hosts: kubernetes
  become: yes
  become_method: sudo

  vars:
    # drop the recursive app_tag definition!
    default_app_tag: latest

    aws_account_id: "732583169994"
    aws_region: "us-east-1"

    kubeconfig_path: /home/ans2admin/.kube/config
    app_deployment_yaml: /var/lib/jenkins/workspace/newdeployment/webapp-deployment.yaml
    app_service_yaml:    /var/lib/jenkins/workspace/newdeployment/webapp-service.yaml

    full_image_path: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/regapp"

  tasks:
    - name: Ensure Deployment YAML exists
      ansible.builtin.stat:
        path: "{{ app_deployment_yaml }}"
      register: deployment_file

    - name: Ensure Service YAML exists
      ansible.builtin.stat:
        path: "{{ app_service_yaml }}"
      register: service_file

    - name: Update Deployment image with new tag
      ansible.builtin.replace:
        path: "{{ app_deployment_yaml }}"
        regexp: '(image:\s*{{ full_image_path }}:)(\S+)'
        replace: 'image: {{ full_image_path }}:{{ app_tag | default(default_app_tag) }}'
      when: deployment_file.stat.exists

    - name: Apply Deployment YAML to Kubernetes
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-deployment.yaml"
      delegate_to: localhost
    
    - name: Apply Service YAML to Kubernetes
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ playbook_dir }}/webapp-service.yaml"
      delegate_to: localhost

    - name: Debug which image tag is being used
      ansible.builtin.debug:
        msg: "🚀 Deploying regapp image: {{ full_image_path }}:{{ app_tag | default(default_app_tag) }}"
