- name: Deploy Webapp to EKS
  hosts: kubernetes
  gather_facts: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3.8
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    # --- install python 3.8 idempotently -----------------
    - name: Enable python3.8 topic
      become: yes
      command: amazon-linux-extras enable python3.8
      args:
        creates: /etc/yum.repos.d/amzn2extra-python3.8.repo   # run once

    - name: Install python38 & pip
      become: yes
      yum:
        name:
          - python38
          - python38-pip
        state: present

    # --- pip bits ----------------------------------------
    - name: Upgrade pip (python3.8)
      become: yes
      command: /usr/bin/python3.8 -m pip install --upgrade pip
      args:
        creates: /usr/local/bin/pip3.8                       # crude idempotency

    - name: Install kubernetes Python client
      become: yes
      pip:
        executable: /usr/bin/python3.8
        name: kubernetes
        state: present

    # --- apply manifests ---------------------------------
    - name: Apply Deployment to EKS
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: "{{ playbook_dir }}/webapp-deployment.yaml"
        state: present

    - name: Apply Service to EKS
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: "{{ playbook_dir }}/webapp-service.yaml"
        state: present
