- name: Deploy Webapp to EKS
  hosts: kubernetes
  gather_facts: yes
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    # … your copy/manifest tasks …

    - name: Ensure pip for Python 3.8 is up to date
      become: yes
      ansible.builtin.shell:
        cmd: /usr/bin/python3.8 -m pip install --upgrade pip
        warn: false

    - name: Install Kubernetes Python client into Python 3.8
      become: yes
      pip:
        name: kubernetes
        executable: /usr/bin/python3.8 -m pip

    - name: Apply Deployment to EKS
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: /home/ec2-user/webapp-deployment.yaml
        state: present

    - name: Apply Service to EKS
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: /home/ec2-user/webapp-service.yaml
        state: present
