- name: Deploy Webapp to EKS
  hosts: kubernetes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Enable Python 3.8 and install pip
      become: yes
      ansible.builtin.shell: |
        amazon-linux-extras enable python3.8
        yum clean metadata
        yum install -y python3.8 python3.8-pip
      args:
        warn: false          # <‑‑ goes under args, not beside the module

    - name: Ensure pip for Python 3.8 is up to date
      become: yes
      ansible.builtin.shell:
        cmd: /usr/bin/python3.8 -m pip install --upgrade pip
        warn: false

    - name: Install Kubernetes Python client into Python 3.8
      become: yes
      ansible.builtin.pip:
        executable: /usr/bin/python3.8 -m pip
        name:
          - kubernetes

    - name: Apply Deployment to EKS
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: "{{ playbook_dir }}/webapp-deployment.yaml"
        state: present

    - name: Apply Service to EKS
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: "{{ playbook_dir }}/webapp-service.yaml"
        state: present
