- name: Deploy Webapp to EKS
  hosts: eks-bootstrap
  gather_facts: yes
  vars:
    kubeconfig_path: /home/ec2-user/.kube/config

  tasks:
    - name: Copy Deployment manifest to bastion
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/webapp-deployment.yaml"
        dest: /home/ec2-user/webapp-deployment.yaml
        mode: 0644

    - name: Copy Service manifest to bastion
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/webapp-service.yaml"
        dest: /home/ec2-user/webapp-service.yaml
        mode: 0644

    - name: Apply Deployment to EKS
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: /home/ec2-user/webapp-deployment.yaml
        state: present

    - name: Apply Service to EKS
      collections:
        - kubernetes.core
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: /home/ec2-user/webapp-service.yaml
        state: present
